SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    ENGINE,
    TABLE_ROWS,
    DATA_LENGTH,
    INDEX_LENGTH,
    DATA_FREE
FROM information_schema.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'
  AND ENGINE IS NOT NULL
  AND TABLE_SCHEMA NOT IN (%s, %s, %s, %s)
ORDER BY DATA_LENGTH + INDEX_LENGTH DESC
LIMIT %s
