SELECT
    OBJECT_SCHEMA,
    OBJECT_NAME,
    COUNT_FETCH,
    SUM_TIMER_FETCH,
    COUNT_INSERT,
    SUM_TIMER_INSERT,
    COUNT_UPDATE,
    SUM_TIMER_UPDATE,
    COUNT_DELETE,
    SUM_TIMER_DELETE
FROM performance_schema.table_io_waits_summary_by_table
WHERE OBJECT_SCHEMA NOT IN (%s, %s, %s, %s)
  AND COUNT_STAR > 0
ORDER BY SUM_TIMER_WAIT DESC
LIMIT %s
